# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
language: cpp
os: linux
dist: trusty
sudo: false
compiler: clang
cache: ccache
addons:
  apt:
    packages: gyp ninja-build python
matrix:
    - os: linux
      compiler: gcc
      sudo : true
      install: ./googletest/ci/install-linux.sh && ./googletest/ci/log-config.sh
      script: ./googletest/ci/build-linux-bazel.sh
    - os: linux
      compiler: clang
      sudo : true
      install: ./googletest/ci/install-linux.sh && ./googletest/ci/log-config.sh
      script: ./googletest/ci/build-linux-bazel.sh
env:
  global:
    - TRAVIS_CI_PATH=$(pwd)   
before_install:
  - pip install --user cpp-coveralls      
install:
  # Download re2 from source because Ubuntu Trusty (the newest version of Ubuntu
  # in Travis-CI) does not include a package. Packages from newer releases of
  # Ubuntu are not binary compatible with Trusty. The re2 shared library is
  # installed into $HOME/usr/local/lib.
  - git clone https://github.com/google/re2.git
  - make -C re2
  - env DESTDIR="$HOME" make -C re2 install
  - git clone https://github.com/google/googletest.git
before_script:
  - git submodule update
  - GTEST_DIR=${TRAVIS_CI_PATH}/googletest/googletest
  - g++ -std=c++11 -isystem ${GTEST_DIR}/include -I${GTEST_DIR} -pthread -c ${GTEST_DIR}/src/gtest-all.cc
  - ar -rv libgtest.a gtest-all.o
  - cd ${GTEST_DIR}/make
  - make
script:
  - cd ${TRAVIS_CI_PATH}/cpp
  - env CXXFLAGS="-I$HOME/usr/local/include -I${GTEST_DIR}/include -I${GTEST_DIR} -I${GTEST_DIR}/make" LDFLAGS="-L$HOME/usr/local/lib -L$(pwd) -L${GTEST_DIR}/include -L${GTEST_DIR} -L${GTEST_DIR}/make" CPPFLAGS="-I${GTEST_DIR}/include -I${GTEST_DIR} -I${GTEST_DIR}/make" GYP_GENERATORS="ninja"  gyp --depth .
  - ninja -C out/Default
after_script:
  - env LD_LIBRARY_PATH="$HOME/usr/local/lib" out/Default/unit_tests
